# Site settings
title: "Issa's Resume"
description: "My personal resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Issa Alkhoury"
resume_title:                   "Tech Lead"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hello@issakhoury.me"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       ""
resume_contact_address:         "Amsterdam, the Netherlands"

resume_header_contact_info:     "Amsterdam, the Netherlands • hello@issakhoury.me"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a passionate Software Engineer and Cloud Architect focused on delivering high quality,
efficient, and reliable solutions. I find interest in designing cloud
native services that help in extracting value out of business data or automating a business
process.</br> My priority in any software project is delivering features to the customer that help them make
the right impact in their organisation. I advocate for the
incremental delivery of value along with continuous evaluation and improvement of the
product. I also believe in cross-functional agile teams that work together in an end-to-end
delivery process while adhering to good software development practices.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ikhoury"
  resume_twitter_url:           "http://twitter.com/issakhoury16"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/issakhoury"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
